import type { ICard } from './Card';

export const CardMockData: ICard = {
    id: 'b2DZoZvr2WEwq8px3Fuca', // ID of the invoice
    shipment: {
        id: '_7pRBN49W3qbIsdiqzYoZ', // ID of the shipment
        createdAt: '2025-10-30T04:01:45.903Z', // date when the shipment was created
        trackingNumber: '208669628341', // tracking number generated by the carrier
        company: {
            id: 'fGZvzkW7AW696vc97qb1-', // ID of the company registered to the Delivro app
            name: 'Lynch - Bartoletti', // name of the registered company
        },
        provider: 'FedEx', // possible providers are GLS, DPD, UPS, PPL, FedEx
        mode: 'IMPORT', // considered an 'EXPORT' if origin country is strictly equal to CZ, otherwise it is always an 'IMPORT'
        originCountry: 'CZ', // ISO code of the origin country
        destinationCountry: 'GP', // ISO code of the destination country
    },
    invoicedWeight: 9.9, // units in KG
    invoicedPrice: 302, // units in CZK
};
